---
# tasks file for setup-agent
- name  : instlation cron
  apt:
      name: "cron"
      state: present

- name : copy fichier
  copy:
   src: agent.yml
   dest: /etc/ansible/playbooks/agent.yml

- name : cron task playbook
  cron:
    minute: "0"
    job: "ansible-playbook /etc/ansible/playbooks/agent.yml"

- name : git clone
  git:
    repo: http://10.10.20.6/root/socle.git
    dest: /etc/ansible/roles/socle
    
- name  : deploiement local socle
  shell : ansible-playbook /etc/ansible/playbooks/agent.yml
