---
# tasks file for ansible-server

#sudo apt-get install -yqq software-properties-common
#sudo apt-add-repository ppa:ansible/ansible
#sudo apt-get -y update
#sudo apt-get install -yqq ansible

- name : instalation software-properties-common
  apt:
      name: ['software-properties-common']
      state: present

- name : ansible repository
  apt_repository:
      repo: 'ppa:ansible/ansible'

- name : Update repositories cache
  apt:
      update_cache: yes

- name : instlation ansible
  apt:
      name: "ansible"
      state: present

